'use client'

import { Grid } from '@mui/material';

import { Providers } from '../redux/provider';
import styles from './layout.module.scss';
import { SideBar } from 'components/SideBar';
import { Footer } from 'components/Footer';
import { Header } from 'components/Header';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body className={styles.root}>
                <Providers>
                    <SideBar />
                    <Grid container >
                        <Grid item xs={11} md={10} lg={8} xl={8} sx={{ mx: 'auto' }}>
                            <Header />
                            {children}
                            <Footer />
                        </Grid>
                    </Grid>
                </Providers>
            </body>
        </html>
    )
}

export default RootLayout;